var _yt_www={};(function(m){var window=this;var pa,qa;m.aa=function(a){return function(){return m.ba[a].apply(this,arguments)}};m.ca=function(a){return void 0!==a};m.l=function(a,b,c){a=a.split(".");c=c||m.da;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&m.ca(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};m.n=function(a,b){for(var c=a.split("."),d=b||m.da,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};m.ea=function(){};m.fa=function(a){a.getInstance=function(){return a.hb?a.hb:a.hb=new a}};
m.ga=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};m.ha=function(a){return"array"==m.ga(a)};m.ia=function(a){var b=m.ga(a);return"array"==b||"object"==b&&"number"==typeof a.length};m.ja=function(a){return"string"==typeof a};m.ka=function(a){return"number"==typeof a};m.la=function(a){return"function"==m.ga(a)};m.na=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};m.oa=function(a){return a[pa]||(a[pa]=++qa)};
var ra=function(a,b,c){return a.call.apply(a.bind,arguments)};var sa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};m.q=function(a,b,c){m.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ra:sa;return m.q.apply(null,arguments)};
m.r=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};m.t=function(a,b){function c(){}c.prototype=b.prototype;a.K=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[c].apply(a,h)}};m.ta=function(a){m.ta[" "](a);return a};
m.ua=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,m.ua);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};m.va=function(a){return(0,window.encodeURIComponent)(String(a))};
m.wa=function(a){if(!xa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ya,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(za,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Aa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Ba,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ca,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Da,"&#0;"));return a};m.Ea=function(a,b){return-1!=a.indexOf(b)};m.Fa=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
m.Ga=function(a,b){for(var c=0,d=(0,m.Ha)(String(a)).split("."),e=(0,m.Ha)(String(b)).split("."),f=Math.max(d.length,e.length),h=0;0==c&&h<f;h++){var k=d[h]||"",p=e[h]||"",w=RegExp("(\\d*)(\\D*)","g"),B=RegExp("(\\d*)(\\D*)","g");do{var P=w.exec(k)||["","",""],Y=B.exec(p)||["","",""];if(0==P[0].length&&0==Y[0].length)break;c=Ia(0==P[1].length?0:(0,window.parseInt)(P[1],10),0==Y[1].length?0:(0,window.parseInt)(Y[1],10))||Ia(0==P[2].length,0==Y[2].length)||Ia(P[2],Y[2])}while(0==c)}return c};
var Ia=function(a,b){return a<b?-1:a>b?1:0};m.Ja=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};m.Ka=function(a){var b=m.ja(void 0)?m.Fa(void 0):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};m.Ma=function(a,b,c){b=m.Na(a,b,c);return 0>b?null:m.ja(a)?a.charAt(b):a[b]};m.Na=function(a,b,c){for(var d=a.length,e=m.ja(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};
m.Oa=function(a,b){return 0<=(0,m.Pa)(a,b)};m.Qa=function(a,b){var c=(0,m.Pa)(a,b),d;(d=0<=c)&&m.Ra(a,c);return d};m.Ra=function(a,b){m.Sa.splice.call(a,b,1)};m.Ta=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};m.u=function(){this.kb=this.kb;this.va=this.va};m.Ua=function(a,b){m.Va(a,m.r(m.Wa,b))};m.Va=function(a,b){a.va||(a.va=[]);a.va.push(m.ca(void 0)?(0,m.q)(b,void 0):b)};m.Wa=function(a){a&&"function"==typeof a.dispose&&a.dispose()};
m.Xa=function(){m.u.call(this);this.wa=[];this.Nb={}};m.Ya=function(a){Za(m.$a,arguments)};m.v=function(a,b){return a in m.$a?m.$a[a]:b};m.x=function(a,b){m.la(a)&&(a=m.ab(a));return window.setTimeout(a,b)};m.bb=function(a,b){m.la(a)&&(a=m.ab(a));return window.setInterval(a,b)};m.cb=function(a){window.clearTimeout(a)};m.db=function(a){window.clearInterval(a)};m.ab=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw m.eb(b),b;}}:a};
m.eb=function(a,b){var c=m.n("yt.www.errors.log");c?c(a,b):(c=m.v("ERRORS")||[],c.push([a,b]),m.Ya("ERRORS",c))};m.fb=function(a){return a in m.gb};m.hb=function(a,b,c){var d=b||{};if(a=a in m.gb?m.gb[a]:c)for(var e in d)a=a.replace(new RegExp("\\$"+e,"gi"),function(){return d[e]});return a};var Za=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};
m.y=function(a,b,c){var d=ib();if(d){var e=d.subscribe(a,function(){if(!m.jb||m.jb!=e){var d=arguments,h=function(){kb[e]&&b.apply(c||window,d)};try{lb[a]?h():m.x(h,0)}catch(k){m.eb(k)}}},c);kb[e]=!0;mb[a]||(mb[a]=[]);mb[a].push(e);return e}return 0};m.nb=function(a){var b=ib();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,m.z)(a,function(a){b.unsubscribeByKey(a);delete kb[a]}))};m.A=function(a,b){var c=ib();return c?c.publish.apply(c,arguments):!1};
m.ob=function(a,b){lb[a]=!0;var c=ib(),c=c?c.publish.apply(c,arguments):!1;lb[a]=!1;return c};var ib=function(){return m.n("yt.pubsub.instance_")};m.pb=function(a){if(a.classList)return a.classList;a=a.className;return m.ja(a)&&a.match(/\S+/g)||[]};m.C=function(a,b){return a.classList?a.classList.contains(b):m.Oa(m.pb(a),b)};m.D=function(a,b){a.classList?a.classList.add(b):m.C(a,b)||(a.className+=0<a.className.length?" "+b:b)};
m.E=function(a,b){a.classList?a.classList.remove(b):m.C(a,b)&&(a.className=(0,m.qb)(m.pb(a),function(a){return a!=b}).join(" "))};m.rb=function(a,b,c){c?m.D(a,b):m.E(a,b)};m.sb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};m.tb=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};m.ub=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};m.vb=function(a,b){b in a&&delete a[b]};m.wb=function(a,b,c){if(b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c};
m.xb=function(a){var b={},c;for(c in a)b[c]=a[c];return b};m.yb=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<zb.length;f++)c=zb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};m.Ab=function(a){var b=arguments.length;if(1==b&&m.ha(arguments[0]))return m.Ab.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};m.Bb=function(){this.g="";this.j=Cb};
var Db=function(a){return a instanceof m.Bb&&a.constructor===m.Bb&&a.j===Cb?a.g:"type_error:Const"};var Eb=function(){this.g="";this.j=Fb};var Gb=function(a){var b=new Eb;b.g=a;return b};var Hb=function(){this.g=Ib};var Jb=function(){this.g=Kb};var Lb=function(){this.g="";this.k=Mb;this.j=null};m.Nb=function(a){return a instanceof Lb&&a.constructor===Lb&&a.k===Mb?a.g:"type_error:SafeHtml"};
m.Ob=function(a,b){if(!Pb.test(a))throw Error("Invalid tag name <"+a+">.");if(a.toLowerCase()in Qb)throw Error("Tag name <"+a+"> is not allowed for SafeHtml.");var c=null,d="<"+a;if(b)for(var e in b){if(!Pb.test(e))throw Error('Invalid attribute name "'+e+'".');var f=b[e];if(null!=f){var h,k=a;h=e;if(f instanceof m.Bb)f=Db(f);else if("style"==h.toLowerCase()){if(!m.na(f))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof f+" given: "+f);if(!(f instanceof
Eb)){var k="",p=void 0;for(p in f){if(!/^[-_a-zA-Z0-9]+$/.test(p))throw Error("Name allows only [-_a-zA-Z0-9], got: "+p);var w=f[p];null!=w&&(w instanceof m.Bb?w=Db(w):Rb.test(w)||(w="zClosurez"),k+=p+":"+w+";")}f=k?Gb(k):Sb}k=void 0;k=f instanceof Eb&&f.constructor===Eb&&f.j===Fb?f.g:"type_error:SafeStyle";f=k}else{if(/^on/i.test(h))throw Error('Attribute "'+h+'" requires goog.string.Const value, "'+f+'" given.');if(h.toLowerCase()in Tb)if(f instanceof Jb)f=f instanceof Jb&&f.constructor===Jb&&f.g===
Kb?"":"type_error:TrustedResourceUrl";else if(f instanceof Hb)f=f instanceof Hb&&f.constructor===Hb&&f.g===Ib?"":"type_error:SafeUrl";else throw Error('Attribute "'+h+'" on tag "'+k+'" requires goog.html.SafeUrl or goog.string.Const value, "'+f+'" given.');}f.af&&(f=f.$e());h=h+'="'+m.wa(String(f))+'"';d=d+(" "+h)}}e=void 0;m.ca(e)?m.ha(e)||(e=[e]):e=[];!0===Ub[a.toLowerCase()]?d+=">":(c=Vb(e),d+=">"+m.Nb(c)+"</"+a+">",c=c.ag());(e=b&&b.dir)&&(/^(ltr|rtl|auto)$/i.test(e)?c=0:c=null);return Xb(d,c)};
var Vb=function(a){function b(a){if(m.ha(a))(0,m.z)(a,b);else{if(!(a instanceof Lb)){var f=null;a.Dk&&(f=a.ag());a=Xb(m.wa(a.af?a.$e():String(a)),f)}d+=m.Nb(a);a=a.ag();0==c?c=a:0!=a&&c!=a&&(c=null)}}var c=0,d="";(0,m.z)(arguments,b);return Xb(d,c)};var Xb=function(a,b){var c=new Lb;c.g=a;c.j=b;return c};m.Yb=function(a,b,c){return Math.min(Math.max(a,b),c)};var Zb=function(a){return m.Ea(m.$b,a)};var ac=function(){var a=m.da.document;return a?a.documentMode:void 0};
m.bc=function(a){return cc[a]||(cc[a]=0<=m.Ga(dc,a))};m.ec=function(a){return m.F&&m.fc>=a};m.G=function(a){return m.ja(a)?window.document.getElementById(a):a};m.gc=function(a){return m.hc(window.document,a)};m.hc=function(a,b){return m.ja(b)?a.getElementById(b):b};m.H=function(a,b){var c=b||window.document,d=null;c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=m.ic("*",a,b)[0];return d||null};
m.ic=function(a,b,c){var d=window.document;c=c||d;a=a&&"*"!=a?a.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(a||b))return c.querySelectorAll(a+(b?"."+b:""));if(b&&c.getElementsByClassName){c=c.getElementsByClassName(b);if(a){for(var d={},e=0,f=0,h;h=c[f];f++)a==h.nodeName&&(d[e++]=h);d.length=e;return d}return c}c=c.getElementsByTagName(a||"*");if(b){d={};for(f=e=0;h=c[f];f++)a=h.className,"function"==typeof a.split&&m.Oa(a.split(/\s+/),b)&&(d[e++]=h);d.length=e;return d}return c};
m.jc=function(a,b){m.sb(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in kc?a.setAttribute(kc[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})};m.lc=function(a,b,c){return m.mc(window.document,arguments)};
m.mc=function(a,b){var c=b[0],d=b[1];if(!nc&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',m.wa(d.name),'"');if(d.type){c.push(' type="',m.wa(d.type),'"');var e={};m.yb(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(m.ja(d)?c.className=d:m.ha(d)?c.className=d.join(" "):m.jc(c,d));2<b.length&&m.oc(a,c,b,2);return c};
m.oc=function(a,b,c,d){function e(c){c&&b.appendChild(m.ja(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];!m.ia(f)||m.na(f)&&0<f.nodeType?e(f):(0,m.z)(pc(f)?m.Ta(f):f,e)}};m.qc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};var rc=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};
var sc=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};m.tc=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};var pc=function(a){if(a&&"number"==typeof a.length){if(m.na(a))return"function"==typeof a.item||"string"==typeof a.item;if(m.la(a))return"function"==typeof a.item}return!1};m.uc=function(a,b,c,d){c||(a=a.parentNode);c=null==d;for(var e=0;a&&(c||e<=d);){if(b(a))return a;a=a.parentNode;e++}return null};
m.vc=function(a){return function(){return a}};m.wc=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};m.xc=function(){};m.yc=function(a){if(a instanceof m.xc)return a;if("function"==typeof a.fb)return a.fb(!1);if(m.ia(a)){var b=0,c=new m.xc;c.next=function(){for(;;){if(b>=a.length)throw m.zc;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");};
m.Ac=function(a,b,c){if(m.ia(a))try{(0,m.z)(a,b,c)}catch(d){if(d!==m.zc)throw d;}else{a=m.yc(a);try{for(;;)b.call(c,a.next(),void 0,a)}catch(e){if(e!==m.zc)throw e;}}};m.Bc=function(a){if(m.ia(a))return m.Ta(a);a=m.yc(a);var b=[];m.Ac(a,function(a){b.push(a)});return b};m.Cc=function(a,b,c,d,e,f,h){var k="";a&&(k+=a+":");c&&(k+="//",b&&(k+=b+"@"),k+=c,d&&(k+=":"+d));e&&(k+=e);f&&(k+="?"+f);h&&(k+="#"+h);return k};
m.Dc=function(a){if(Ec){Ec=!1;var b=m.da.location;if(b){var c=b.href;if(c&&(c=m.Fc(c))&&c!=b.hostname)throw Ec=!0,Error();}}return a.match(Gc)};m.Hc=function(a){return a?(0,window.decodeURI)(a):a};m.Fc=function(a){return m.Hc(m.Dc(a)[3]||null)};m.Ic=function(a){a=m.Dc(a);return m.Cc(null,null,null,null,a[5],a[6],a[7])};m.Jc=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};
m.Kc=function(a,b,c){if(m.ha(b))for(var d=0;d<b.length;d++)m.Kc(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",m.va(b))};var Lc=function(a,b){for(var c in b)m.Kc(c,b[c],a);return a};m.Mc=function(a){a=Lc([],a);a[0]="";return a.join("")};m.Nc=function(a,b){return m.Jc(Lc([a],b))};m.Oc=function(a,b,c){a&&(c?a&&(a=m.lc("iframe",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),m.tc(a).body.appendChild(a)):Pc(a,b))};
var Pc=function(a,b){var c=new window.Image,d=""+Qc++;Rc[d]=c;c.onload=c.onerror=function(){b&&Rc[d]&&b();delete Rc[d]};c.src=a;c=eval("null")};m.Sc=function(a,b,c){Tc(c)[a]=b||(0,m.I)();b||Uc(a)};var Vc=function(a,b){Wc(void 0).yt_sts=a;m.Sc("_start",b,void 0)};var Xc=function(a){return Math.round(Yc.timing.navigationStart+a)};
var Zc=function(a){var b=window.location.protocol,c=Yc.getEntriesByType("resource"),d=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.googleapis.com/css?family=")})[0],c=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.gstatic.com/s/")}).reduce(function(a,b){return b.duration>a.duration?b:a},{duration:0});d&&0<d.startTime&&0<d.responseEnd&&(a.wfcs=Xc(d.startTime),a.wfce=Xc(d.responseEnd));c&&0<c.startTime&&0<c.responseEnd&&(a.wffs=Xc(c.startTime),a.wffe=Xc(c.responseEnd))};
var $c=function(a){var b=Tc(a),c=ad(a).span,d=Wc(a),e=m.n("yt.timing.reportbuilder_");if(e){if(e=e(b,c,d,a))bd(e),cd(a),dd();return window.NaN}e={v:2,s:"youtube",action:m.v("TIMING_ACTION")};if(Yc.now&&Yc.timing){var f=Yc.timing.navigationStart+Yc.now(),f=Math.round((0,m.I)()-f);d.yt_hrd=f}var f=m.v("TIMING_INFO")||{},h;for(h in f)d[h]=f[h];h=d.srt;delete d.srt;var k;h||0===h||(k=Yc.timing||{},h=Math.max(0,k.responseStart-k.navigationStart),(0,window.isNaN)(h)&&d.pt&&(h=d.pt));if(h||0===h)d.srt=h;
d.h5jse&&(f=window.location.protocol+m.n("ytplayer.config.assets.js"),(f=Yc.getEntriesByName?Yc.getEntriesByName(f)[0]:null)?d.h5jse=Math.round(d.h5jse-f.responseEnd):delete d.h5jse);b.aft||(b.aft=b.pbr&&b.pbs>b.pbr?b.pbr:b.pbs?b.pbs:b.vr?b.vr:b.ol);f=b._start;if(!ed){k||(k=Yc.timing||{});var p;t:if(p=k,p.msFirstPaint)p=Math.max(0,p.msFirstPaint);else{var w=window.chrome;if(w&&(w=w.loadTimes,m.la(w))){var w=w(),B=1E3*Math.min(w.requestTime||window.Infinity,w.startLoadTime||window.Infinity),B=window.Infinity===
B?0:p.navigationStart-B;p=Math.max(0,Math.round(1E3*w.firstPaintTime+B)||0);break t}p=0}0<p&&p>f&&(b.fpt=p);p=k.redirectEnd-k.redirectStart;0<p&&(c.rtime_=p);p=k.domainLookupEnd-k.domainLookupStart;0<p&&(c.dns_=p);p=k.connectEnd-k.connectStart;0<p&&(c.tcp_=p);p=k.connectEnd-k.secureConnectionStart;k.secureConnectionStart&&0<p&&(c.stcp_=p);p=k.responseStart-k.requestStart;0<p&&(c.req_=p);p=k.responseEnd-k.responseStart;0<p&&(c.rcv_=p);m.v("EXP_WEBFONT_ENABLED")&&Yc.getEntriesByType&&Zc(b);ed=!0}for(var P in d)"_"!=
P.charAt(0)&&(e[P]=d[P]);d={};P=[];for(var Y in b)"_"!=Y.charAt(0)&&(p=Math.max(Math.round(b[Y]-f),0),d[Y]=p,P.push(Y+"."+p));e.rt=P.join(",");b={};Y=[];for(var ma in c)"_"!=ma.charAt(0)&&(b[ma]=c[ma],Y.push(ma+"."+c[ma]));e.it=Y.join(",");(c=m.n("ytdebug.logTiming"))&&c(e,d,b);cd(a);dd();m.v("EXP_DEFER_CSI_PING")?(fd(),gd=e,hd=m.x(fd,0)):bd(e);return d.aft+(h||0)};
var id=function(a,b){var c=m.v("TIMING_ACTION"),d=Tc(b);if(c&&d._start)if(c=m.v("TIMING_WAIT",[]),!a&&c.length){for(var e=!0,f=0,h=c.length;f<h;++f)if(!(c[f]in d)){e=!1;break}if(e)return $c(b)}else if(d.ol||d.aft)return $c(b);return window.NaN};var jd=function(a){if(m.v("TIMING_WAIT"))a=id(!1,a);else t:{var b=m.v("TIMING_ACTION"),c=!!m.v("TIMING_WFF"),d=Tc(a);if(b&&d._start){if(c&&d.vr||!c&&(d.ol||d.aft)){a=$c(a);break t}a&&$c(a)}a=window.NaN}return a};
var bd=function(a){m.v("EXP_DEFER_CSI_PING")&&(m.cb(hd),gd=null);var b="https:"==window.location.protocol?"https://gg.google.com/csi":"http://csi.gstatic.com/csi",c="",d;for(d in a)c+="&"+d+"="+a[d];m.Oc(b+"?"+c.substring(1))};var fd=function(a){gd&&(a&&(gd.yt_fss=a),bd(gd))};var Tc=function(a){return ad(a).tick};var Wc=function(a){return ad(a).info};var ad=function(a){return m.n("ytcsi."+(a||"")+"data_")||cd(a)};
var cd=function(a){var b={tick:{},span:{},info:{}};m.l("ytcsi."+(a||"")+"data_",b,void 0);return b};m.kd=function(){return!!m.n("yt.scheduler.instance")};m.ld=function(){return m.kd()&&m.C(window.document.body,"exp-js-scheduler-more")};m.md=function(a,b){void 0===b&&(b=window.NaN);var c=m.n("yt.scheduler.instance.addJob");return c?((0,window.isNaN)(b)&&(b=0),c(a,0,b)):(0,window.isNaN)(b)?(a(),window.NaN):m.x(a,b||0)};m.nd=function(a,b){return m.md(a,b)};
m.od=function(a){var b=m.n("yt.scheduler.instance.cancelJob");b?b(a):m.cb(a)};m.pd=function(a){for(var b=0,c=a.length;b<c;b++)m.od(a[b])};m.qd=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.B=d?m.ab(d):null;this.A=e?m.ab(e):null;this.wa=[];this.j=this.k=0};m.rd=function(a){m.ld()?(m.od(a.k),a.k=m.nd((0,m.q)(a.init,a))):a.init()};
m.sd=function(a){a.name in td&&ud(a.name);td[a.name]={reqs:[],disable:(0,m.q)(a.disable,a)};(0,m.z)(a.deps,function(b){if(!(b in td))throw Error("Module "+b+" required by "+a.name);td[b].reqs.push(a.name)});a.enable()};var ud=function(a){if(a in td){var b=td[a];(0,m.z)(b.reqs,function(a){ud(a)});try{b.disable()}catch(c){}delete td[a]}};m.J=function(a,b){return a?a.dataset?a.dataset[m.vd(b)]:a.getAttribute("data-"+b):null};
m.wd=function(a,b){return a?a.dataset?m.vd(b)in a.dataset:a.hasAttribute?!!a.hasAttribute("data-"+b):!!a.getAttribute("data-"+b):!1};m.vd=function(a){return xd[a]||(xd[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};m.yd=function(a,b){var c=m.zd(a);window.spf.script.load(a,c,b)};m.Ad=function(a,b){var c=m.zd(a);window.spf.script.ignore(c,b)};m.Bd=function(a){a&&(m.ja(a)?m.yd(a):m.ha(a)?(0,m.z)(a,function(a){m.Bd(a)}):m.sb(a,function(a,c){m.yd(c,function(){m.Bd(a)})}))};
m.zd=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(Cd,""),b=b.replace(Dd,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};var Ed=function(a){a=m.Fd(a);return m.Gd(a)||(null===a?!1:"google"==a[1]?!0:"google"==a[2]?"au"==a[0]&&"com"==a[1]?!0:"uk"==a[0]&&"co"==a[1]?!0:!1:!1)};m.Gd=function(a){return null===a?!1:"com"==a[0]&&a[1].match(/^youtube(?:-nocookie)?$/)?!0:!1};
m.Fd=function(a){a=(0,m.Hd)(a);return null===a?null:a.split(".").reverse()};m.Id=function(a,b){m.Oc("/gen_204?"+a,b)};
var Jd=function(a){a=a||{};this.url=a.url||"";this.urlV8=a.url_v8||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||m.xb(Kd);this.assets=a.assets||{};this.attrs=a.attrs||m.xb(Ld);this.params=a.params||m.xb(Md);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};m.Nd=function(a){a instanceof Jd||(a=new Jd(a));return a};
var Od=function(){return null!=m.Pd};m.Qd=function(){return m.Pd?m.Pd.invoke():null};m.Rd=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,m.z)(a.childNodes,function(a){b.appendChild(m.Rd(a))}):b.innerHTML=a.innerHTML;return b};
m.Sd=function(a){if(a=a||window.event){for(var b in a)b in Td||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;this.ua=a;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:
a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;"MozMousePixelScroll"==this.type?(this.wheelDeltaX=a.axis==a.HORIZONTAL_AXIS?a.detail:0,this.wheelDeltaY=a.axis==a.HORIZONTAL_AXIS?0:a.detail):window.opera?(this.wheelDeltaX=0,this.wheelDeltaY=a.detail):0==a.wheelDelta%120?"WebkitTransform"in window.document.documentElement.style?window.chrome&&0==window.navigator.platform.indexOf("Mac")?(this.wheelDeltaX=a.wheelDeltaX/
-30,this.wheelDeltaY=a.wheelDeltaY/-30):(this.wheelDeltaX=a.wheelDeltaX/-1.2,this.wheelDeltaY=a.wheelDeltaY/-1.2):(this.wheelDeltaX=0,this.wheelDeltaY=a.wheelDelta/-1.6):(this.wheelDeltaX=a.wheelDeltaX/-3,this.wheelDeltaY=a.wheelDeltaY/-3);this.Bk=a.pageX;this.Ck=a.pageY}};m.Ud=function(a,b,c,d){return m.ub(m.Vd,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
m.K=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=m.Ud(a,b,c,d);if(e)return e;var e=++Wd.count+"",f=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),h;h=f?function(d){d=new m.Sd(d);if(!m.uc(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new m.Sd(b);b.currentTarget=a;return c.call(a,b)};h=m.ab(h);m.Vd[e]=[a,b,c,h,d];a.addEventListener?"mouseenter"==b&&f?a.addEventListener("mouseover",
h,d):"mouseleave"==b&&f?a.addEventListener("mouseout",h,d):"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style?a.addEventListener("MozMousePixelScroll",h,d):a.addEventListener(b,h,d):a.attachEvent("on"+b,h);return e};m.Xd=function(a){this.g=a};m.Yd=function(a){a=(a.g.cookie||"").split(m.Zd);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
m.$d=function(a,b,c){m.ae.set(""+a,b,c,"/","youtube.com")};m.be=function(a,b){return m.ae.get(""+a,b)};m.ce=function(a,b){a=!!a;m.l("_lactCookie",a,window);if(null==m.n("_lact",window)){if(a&&b){var c=m.be("ACTIVITY","-1");m.l("_lact",(0,window.parseInt)(c,10),window)}else m.l("_lact",-1,window),de();m.K(window.document,"keypress",de);m.K(window.document,"mousedown",de);m.K(window.document,"mouseup",de)}};
var de=function(){var a=m.n("_lact",window);null==a&&(m.ce(),a=m.n("_lact",window));var b=(0,m.I)();m.l("_lact",b,window);m.n("_lactCookie",window)&&1E3<=b-a&&m.$d("ACTIVITY",""+b)};m.ee=function(){var a=m.n("_lact",window);return null==a?-1:Math.max((0,m.I)()-a,0)};m.fe=function(a,b,c){var d=m.Fc(a);if(d==m.Fc(window.location.href)||!d&&0==a.lastIndexOf("/",0))if(a=m.Ic(a),d=a.indexOf("#"),a=0>d?a:a.substr(0,d))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&ge(a,b,c)):ge(a,b)};
var ge=function(a,b,c){for(var d=0,e=0;e<a.length;++e)d=31*d+a.charCodeAt(e),d%=4294967296;a="s_tempdata-"+d;c=c||5;b=b?m.Mc(b):"";m.$d(a,b,c)};m.he=function(a,b,c){c=c||"";window.location=m.Nc(a,b||{})+c};m.ie=function(a,b){var c=window.ytspf||{};b&&m.fe(a,b);c.enabled?window.spf.navigate(a):m.he(a)};m.je=function(a,b,c){var d=m.v("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&m.fe(a,b);if(c)return!1;m.ie(a);return!0};var ke=function(a){m.da.setTimeout(function(){throw a;},0)};
var le=function(){var a=m.da.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(a=function(){var a=window.document.createElement("iframe");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,m.q)(function(a){if(("*"==d||a.origin==
d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!Zb("Trident")&&!Zb("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(m.ca(c.next)){c=c.next;var a=c.Gp;c.Gp=null;a()}};return function(a){d.next={Gp:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("script")?function(a){var b=
window.document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){m.da.setTimeout(a,0)}};var me=function(a,b){ne||oe();pe||(ne(),pe=!0);qe.push(new re(a,b))};
var oe=function(){if(m.da.Promise&&m.da.Promise.resolve){var a=m.da.Promise.resolve();ne=function(){a.then(se)}}else ne=function(){var a=se;!m.la(m.da.setImmediate)||m.da.Window&&m.da.Window.prototype.setImmediate==m.da.setImmediate?(te||(te=le()),te(a)):m.da.setImmediate(a)}};var se=function(){for(;qe.length;){var a=qe;qe=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.re.call(c.scope)}catch(d){ke(d)}}}pe=!1};var re=function(a,b){this.re=a;this.scope=b};
m.ue=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};m.ve=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};m.we=function(a,b){this.j=0;this.C=void 0;this.g=this.k=null;this.A=this.B=!1;try{var c=this;a.call(b,function(a){xe(c,2,a)},function(a){xe(c,3,a)})}catch(d){xe(this,3,d)}};m.ye=function(a){return new m.we(function(b){b(a)})};
var ze=function(a,b){if(0==a.j)if(a.k){var c=a.k;if(c.g){for(var d=0,e=-1,f=0,h;h=c.g[f];f++)if(h=h.If)if(d++,h==a&&(e=f),0<=e&&1<d)break;0<=e&&(0==c.j&&1==d?ze(c,b):(d=c.g.splice(e,1)[0],Ae(c,d,3,b)))}}else xe(a,3,b)};var Be=function(a,b){a.g&&a.g.length||2!=a.j&&3!=a.j||Ce(a);a.g||(a.g=[]);a.g.push(b)};
m.De=function(a,b,c,d){var e={If:null,Gn:null,Hn:null};e.If=new m.we(function(a,h){e.Gn=b?function(c){try{var e=b.call(d,c);a(e)}catch(w){h(w)}}:a;e.Hn=c?function(b){try{var e=c.call(d,b);!m.ca(e)&&b instanceof Ee?h(b):a(e)}catch(w){h(w)}}:h});e.If.k=a;Be(a,e);return e.If};
var xe=function(a,b,c){if(0==a.j){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(m.ve(c)){a.j=1;c.then(a.G,a.J,a);return}if(m.na(c))try{var d=c.then;if(m.la(d)){Fe(a,c,d);return}}catch(e){b=3,c=e}}a.C=c;a.j=b;Ce(a);3!=b||c instanceof Ee||Ge(a,c)}};var Fe=function(a,b,c){function d(b){f||(f=!0,a.J(b))}function e(b){f||(f=!0,a.G(b))}a.j=1;var f=!1;try{c.call(b,e,d)}catch(h){d(h)}};var Ce=function(a){a.B||(a.B=!0,me(a.H,a))};
var Ae=function(a,b,c,d){if(2==c)b.Gn(d);else{if(b.If)for(;a&&a.A;a=a.k)a.A=!1;b.Hn(d)}};var Ge=function(a,b){a.A=!0;me(function(){a.A&&He.call(null,b)})};var Ee=function(a){m.ua.call(this,a)};var Ie=function(a){this.k=a;this.j=null;var b=this;a.then(function(a){b.j=a})};
var Je=function(a,b){var c=b||{},d=Ke().then(function(b){return b(a,{apiKey:c.of||c.apiKey,environment:c.pf||c.environment,helpCenterPath:c.kA||c.helpCenterPath,locale:c.locale||c.locale,productData:c.lA||c.productData,receiverUri:c.mA||c.receiverUri,theme:c.theme||c.theme,window:c.window||c.window})});return new Ie(d)};
var Ke=function(){if(Le)return Le;var a=m.n("help.service.Lazy.create");return a?Le=m.ye(a):Le=(new m.we(function(a,c){var d=window.document.createElement("script");d.async=!0;d.src="https://www.gstatic.com/inproduct_help/service/lazy.min.js";d.onload=d.onreadystatechange=function(){d.readyState&&"loaded"!=d.readyState&&"complete"!=d.readyState||a(null)};d.onerror=c;(window.document.head||window.document.getElementsByTagName("head")[0]).appendChild(d)})).then(function(){var a=m.n("help.service.Lazy.create");
if(!a)throw Error("Failed to load help.service.Lazy.create from https://www.gstatic.com/inproduct_help/service/lazy.min.js");return a})};var Me=function(a,b,c){a.k.then(function(a){a[b].apply(a,c)})};var Oe=function(a){a=a.match(/[\d]+/g);if(!a)return"";a.length=3;return a.join(".")};var Pe=function(a){return(a=a.exec(m.$b))?a[1]:""};
var Qe=function(){this.k=this.j=this.g=0;this.A="";var a=m.n("window.navigator.plugins"),b=m.n("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,f=c.length;e<f;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==a.charAt(0)||
"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.A=b;b=a;this.g=b[0];this.j=b[1];this.k=b[2];if(0>=this.g){var h,k,p,w;if(m.Re)try{h=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(B){h=null}else p=window.document.body,w=window.document.createElement("object"),w.setAttribute("type","application/x-shockwave-flash"),h=p.appendChild(w);if(h&&"GetVariable"in h)try{k=h.GetVariable("$version")}catch(P){k=""}p&&w&&p.removeChild(w);(h=k||"")?(h=h.split(" ")[1].split(","),
h=[(0,window.parseInt)(h[0],10)||0,(0,window.parseInt)(h[1],10)||0,(0,window.parseInt)(h[2],10)||0]):h=[0,0,0];this.g=h[0];this.j=h[1];this.k=h[2]}};var Se=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.g>b[0]||a.g==b[0]&&a.j>b[1]||a.g==b[0]&&a.j==b[1]&&a.k>=b[2]};
var Te=function(a){return-1<a.A.indexOf("Gnash")&&-1==a.A.indexOf("AVM2")||9==a.g&&1==a.j||9==a.g&&0==a.j&&1==a.k?!1:9<=a.g};var Ue=function(a){return m.Ve?!Se(a,11,2):m.We?!Se(a,11,3):!Te(a)};m.Xe=function(){return m.Ye?"Webkit":m.Ze?"Moz":m.F?"ms":m.$e?"O":null};m.af=function(){return m.Ye?"-webkit":m.Ze?"-moz":m.F?"-ms":m.$e?"-o":null};m.bf=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
m.cf=function(a,b){return a&&b?b instanceof m.bf?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};m.df=function(a,b){var c=m.Ja(b);if(void 0===a.style[c]){var d=m.Xe()+m.Ka(c);if(void 0!==a.style[d])return d}return c};m.ef=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};m.ff=function(a,b){a.style.display=b?"":"none"};m.gf=function(a,b){(a=m.G(a))&&a.style&&(m.ff(a,b),m.rb(a,"hid",!b))};
m.L=function(a){(0,m.z)(arguments,function(a){m.gf(a,!0)})};var hf=function(a,b){var c=m.v("FEEDBACK_LOCALE_LANGUAGE"),d=m.jf,e=m.v("FEEDBACK_LOCALE_EXTRAS",{});a?m.yb(d,a):m.yb(d,e);try{var f,h=m.n("yt.player.getPlayerByElement");(f=h?h("player-api"):null)&&f.pauseVideo&&f.pauseVideo();var k=Qe.getInstance();d.flashVersion=k.getVersion().join(".");f&&(d.playback_id=f.getVideoData().cpn)}catch(p){}b&&m.yb(d,{trackingParam:b});return{helpCenterPath:"/youtube",locale:c,productData:d}};
var kf=function(){var a=m.v("SESSION_INDEX"),b=m.v("FEEDBACK_BUCKET_ID"),c={abuseLink:"https://support.google.com/youtube/bin/answer.py?answer=140536",customZIndex:"2000000005"};a&&(c.authuser=a+"");b&&(c.bucket=b);return c};m.lf=function(a,b){try{var c=(a||"59")+"",d=hf(b),e=kf();Je(c,d).A(e);return!1}catch(f){return!0}};
m.mf=function(a,b,c,d,e,f,h,k){b=(b||"59")+"";d=hf(d,h);a={context:c,anchor:a,enableSendFeedback:f?!1:!0,defaultHelpArticleId:k};m.yb(a,kf());try{var p=Je(b,d);if(e&&!nf)try{p.g(a),nf=!0}catch(w){}p.B(a);return!1}catch(B){return!0}};m.of=function(a,b,c,d){return m.mf(void 0,d,b,c,void 0,void 0,void 0,a)};m.pf=function(){var a=m.be("PREF");if(a)for(var a=(0,window.unescape)(a).split("&"),b=0;b<a.length;b++){var c=a[b].split("="),d=c[0];(c=c[1])&&(m.qf[d]=c.toString())}};
var rf=function(a){if(/^f([1-9][0-9]*)$/.test(a))throw"ExpectedRegexMatch: "+a;};var sf=function(a){if(!/^\w+$/.test(a))throw"ExpectedRegexMismatch: "+a;};m.tf=function(a){a=void 0!==m.qf[a]?m.qf[a].toString():null;return null!=a&&/^[A-Fa-f0-9]+$/.test(a)?(0,window.parseInt)(a,16):null};m.uf=function(a,b){return!!((m.tf("f"+(Math.floor(b/31)+1))||0)&1<<b%31)};
var vf=function(a,b,c){if(b){a=m.ja(a)?m.gc(a):a;c=m.Nd(c);var d=m.xb(c.attrs);d.tabindex=0;var e=m.xb(c.params);e.flashvars=m.Mc(c.args);if(m.Re){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var f in d)b.setAttribute(f,d[f]);for(f in e)d=window.document.createElement("param"),d.setAttribute("name",f),d.setAttribute("value",e[f]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");
b.setAttribute("name",d.id);for(f in d)b.setAttribute(f,d[f]);for(f in e)b.setAttribute(f,e[f])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};m.wf=function(a,b){a=m.ja(a)?m.gc(a):a;b=m.Nd(b);if(window!=window.top){var c=null;window.document.referrer&&(c=window.document.referrer.substring(0,128));b.args.framer=c}c=xf();Se(c,b.minVersion)?(c=yf(b,c),vf(a,c,b)):zf(a,b,c)};
var Af=function(a,b,c){if(a&&a.attrs&&a.attrs.id){a=m.Nd(a);var d=!!b,e=m.G(a.attrs.id),f=e?e.parentNode:null;if(e&&f){if(window!=window.top){var h=null;if(window.document.referrer){var k=window.document.referrer.substring(0,128);Ed(k)||(h=k)}else h="unknown";h&&(d=!0,a.args.framer=h)}h=xf();if(Se(h,a.minVersion)){var k=yf(a,h),p="";-1<window.navigator.userAgent.indexOf("Sony/COM2")||(p=e.getAttribute("src")||e.movie);(p!=k||d)&&vf(f,k,a);Ue(h)&&Bf()}else zf(f,a,h);c&&c()}else m.x(function(){Af(a,
b,c)},50)}};var zf=function(a,b,c){0==c.g&&b.fallback?b.fallback():0==c.g&&b.fallbackMessage?b.fallbackMessage():a.innerHTML='<div id="flash-upgrade">'+m.hb("FLASH_UPGRADE",void 0,'You need to upgrade your Adobe Flash Player to watchthis video. <br> <a href="http://get.adobe.com/flashplayer/">Download it from Adobe.</a>')+"</div>"};var yf=function(a,b){var c;(c=Te(b)&&a.url)||(c=(-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!Se(b,9,1,58)?!1:!0)&&a.urlV9As2);return c||a.urlV8||a.url};
var xf=function(){var a=Qe.getInstance(),b=m.pf.getInstance();b.set("fv",a.getVersion().join("."));b.save();return a};var Bf=function(){var a=m.G("flash10-promo-div"),b=m.uf(m.pf.getInstance(),107);a&&!b&&m.L(a)};m.Cf=function(a,b){var c=a.match(Df);window.spf.style.load(a,c?c[1]:"",b)};
var Ef=function(){if(2.2==Ff)return!0;var a;a=m.n("yt.player.utils.videoElement_");a||(a=window.document.createElement("video"),m.l("yt.player.utils.videoElement_",a,void 0));try{return!(!a||!a.canPlayType||!a.canPlayType('video/mp4; codecs="avc1.42001E, mp4a.40.2"')&&!a.canPlayType('video/webm; codecs="vp8.0, vorbis"'))}catch(b){return!1}};var Gf=function(){};m.Hf=function(){};m.If=function(a){this.g=a};m.Jf=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.g=a};
var Kf=function(){var a=null;try{a=window.sessionStorage||null}catch(b){}this.g=a};m.Lf=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};m.Mf=function(a){return m.Nf(new m.Of(void 0),a)};
m.Of=function(a){this.g=a};m.Nf=function(a,b){var c=[];Pf(a,b,c);return c.join("")};
var Pf=function(a,b,c){switch(typeof b){case "string":Qf(b,c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(m.ha(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],Pf(a,a.g?a.g.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&
(c.push(d),Qf(f,c),c.push(":"),Pf(a,a.g?a.g.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}};var Qf=function(a,b){b.push('"',a.replace(Rf,function(a){if(a in Sf)return Sf[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return Sf[a]=e+b.toString(16)}),'"')};m.Tf=function(a){this.g=a};var Uf=function(a){this.g=a};var Vf=function(a){this.data=a};var Wf=function(a){return!m.ca(a)||a instanceof Vf?a:new Vf(a)};
var Xf=function(a){this.g=a};m.Yf=function(a){var b=a.creation;a=a.expiration;return!!a&&a<(0,m.I)()||!!b&&b>(0,m.I)()};m.Zf=function(a){this.g=a};m.$f=function(a,b,c){var d=c&&0<c?c:0;c=d?(0,m.I)()+1E3*d:0;if((d=d?m.ag:m.bg)&&window.JSON){m.ja(b)||(b=JSON.stringify(b,void 0));try{d.set(a,b,c)}catch(e){d.remove(a)}}};m.cg=function(a){if(!m.bg&&!m.ag||!window.JSON)return null;var b;try{b=m.bg.get(a)}catch(c){}if(!m.ja(b))try{b=m.ag.get(a)}catch(d){}if(!m.ja(b))return null;try{b=JSON.parse(b,void 0)}catch(e){}return b};
var dg=function(){var a={volume:100,muted:!1},b=m.cg("yt-player-volume")||{};a.volume=(0,window.isNaN)(b.volume)?100:m.Yb(b.volume,0,100);a.muted=void 0==b.muted?!1:b.muted;return a};
var eg=function(a,b){m.u.call(this);this.k=this.vf=a;this.H=b;this.C=!1;this.g={};this.U=this.J=null;this.O=new m.Xa;m.Ua(this,this.O);this.A={};this.B=this.X=this.j=this.Aa=this.da=null;this.N=!1;this.ga=this.G=null;this.$={};this.Fa=["onReady"];this.oa=null;this.za=0;this.T={};fg(this);this.ue("onVolumeChange",(0,m.q)(this.Rp,this));this.ue("onError",(0,m.q)(this.Qp,this));this.ue("onTabOrderChange",(0,m.q)(this.Pp,this));this.ue("WATCH_LATER_VIDEO_ADDED",(0,m.q)(this.Sp,this));this.ue("WATCH_LATER_VIDEO_REMOVED",
(0,m.q)(this.Tp,this))};
var gg=function(a,b){a.Aa=b;a.da=b.clone();a.j=a.da.attrs.id||a.j;"video-player"==a.j&&(a.j=a.H,a.da.attrs.id=a.H);a.k.id==a.j&&(a.j=a.j+"-player",a.da.attrs.id=a.j);var c=a.da.args,d;(d=a.da.args.eurl)||(d=(d=window.document.location.toString())&&-1!=d.search(hg)?window.document.referrer&&window.document.referrer.substring(0,128)||"unknown":d);c.eurl=d;a.da.args.enablejsapi="1";a.da.args.playerapiid=a.H;a.X||(a.X=ig(a,a.da.args.jsapicallback||"onYouTubePlayerReady"));a.da.args.jsapicallback=null;
if(c=a.da.attrs.width)a.k.style.width=m.ef(Number(c)||c,!0);if(c=a.da.attrs.height)a.k.style.height=m.ef(Number(c)||c,!0);a.k.style.overflow="hidden"};var jg=function(a){a.da.loaded||(a.da.loaded=!0,"0"!=a.da.args.autoplay?a.g.loadVideoByPlayerVars(a.da.args):a.g.cueVideoByPlayerVars(a.da.args))};var kg=function(a){if(!m.ca(a.da.disable.flash)){var b=a.da.disable,c;c=Se(xf(),a.da.minVersion);b.flash=!c}return!a.da.disable.flash};
var lg=function(a){var b=mg(a);b&&b.stopVideo&&b.stopVideo();if(kg(a)){var c=a.da;b&&b.getUpdatedConfigurationData&&(b=m.Nd(b.getUpdatedConfigurationData()),b.args.video_id==c.args.video_id&&(c=b));c.args.autoplay=1;c.args.html5_unavailable="1";gg(a,c);ng(a,"flash")}};
var ng=function(a,b){if(!a.fa()){if(!b){var c;if(!(c=!a.da.html5&&kg(a))){if(!m.ca(a.da.disable.html5)){if(c=Ef())c=og(a)||a.da.assets.js;a.da.disable.html5=!c;c||(a.da.args.html5_unavailable="1")}c=!!a.da.disable.html5}b=c?kg(a)?"flash":"unsupported":"html5"}("flash"==b?a.Ey:"html5"==b?a.Fy:a.Gy).call(a)}};var og=function(a){var b=!0,c=mg(a);c&&a.da&&(a=a.da,b=m.J(c,"version")==a.assets.js);return b&&!!m.n("yt.player.Application.create")};
var mg=function(a){var b=m.G(a.j);!b&&a.k&&a.k.querySelector&&(b=a.k.querySelector("#"+a.j));return b};var pg=function(a,b,c){var d=b[c];return function(){try{return a.oa=null,d.apply(b,arguments)}catch(e){"Bad NPObject as private data!"!=e.message&&(e.message+=" ("+c+")",a.oa=e,m.eb(e,"WARNING"))}}};
var fg=function(a){a.C=!1;if(a.U)for(var b in a.A)a.U(b,a.A[b]);for(var c in a.T)m.cb((0,window.parseInt)(c,10));a.T={};a.J=null;a.U=null;for(var d in a.g)a.g[d]=null;a.g.addEventListener=(0,m.q)(a.ue,a);a.g.removeEventListener=(0,m.q)(a.zt,a);a.g.destroy=(0,m.q)(a.dispose,a);a.g.getLastError=(0,m.q)(a.wt,a);a.g.getPlayerType=(0,m.q)(a.xt,a);a.g.getCurrentVideoConfig=(0,m.q)(a.vt,a);a.g.loadNewVideoConfig=(0,m.q)(a.lj,a);a.g.isReady=(0,m.q)(a.At,a)};
var ig=function(a,b){var c=b;if("string"==typeof b){if(a.$[b])return a.$[b];c=function(){var a=m.n(b);a&&a.apply(m.da,arguments)};a.$[b]=c}return c?c:null};var qg=function(a,b){var c="ytPlayer"+b+a.H;a.A[b]=c;m.da[c]=function(c){var e=m.x(function(){a.fa()||(a.O.publish(b,c),m.vb(a.T,e.toString()))},0);m.wb(a.T,e.toString(),!0)};return c};var rg=function(a){return(a=mg(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
var sg=function(a){m.Sc("dcp");a.cancel();fg(a);a.B=null;a.da&&(a.da.loaded=!1);var b=mg(a);"html5"==rg(a)?a.ga=b:b&&b.destroy&&b.destroy();m.qc(a.vf)};m.tg=function(a,b){a=m.ja(a)?m.gc(a):a;b=m.Nd(b);var c=ug+"_"+m.oa(a),d=vg[c];if(d)return d.lj(b),d.g;d=new eg(a,c);vg[c]=d;m.A("player-added",d.g);m.Va(d,m.r(wg,d));m.x(function(){d.lj(b)},0);return d.g};var xg=function(){for(var a in vg){var b=vg[a];b&&b.cancel()}};m.yg=function(a){if(a=m.G(a))a=ug+"_"+m.oa(a),(a=vg[a])&&a.dispose()};
var wg=function(a){vg[a.getId()]=null};m.Ag=function(a){a=m.G(a);if(!a)return null;var b=ug+"_"+m.oa(a),c=vg[b];c||(c=new eg(a,b),vg[b]=c);return c.g};
var Bg=function(){m.l("yt.abuse.botguardInitialized",Od,void 0);m.l("yt.abuse.invokeBotguard",m.Qd,void 0);m.l("yt.player.exports.navigate",m.je,void 0);m.l("yt.player.embed",m.tg,void 0);m.l("yt.player.destroy",m.yg,void 0);m.l("yt.player.cancelAll",xg,void 0);m.l("yt.player.getPlayerByElement",m.Ag,void 0);m.l("yt.player.exports.feedbackStart",m.lf,void 0);m.l("yt.player.exports.feedbackShowArticle",m.of,void 0);m.l("yt.util.activity.init",m.ce,void 0);m.l("yt.util.activity.getTimeSinceActive",
m.ee,void 0);m.l("yt.util.activity.setTimestamp",de,void 0);var a=m.n("ytplayer.config");Cg(a);m.n("ytspf.enabled")&&(Dg=m.bb(Eg,5E3),(a=m.Fg())?(a.addEventListener("onReady",Eg),a.addEventListener("onStateChange",Eg)):Gg("unable to init PP monitor"))};var Cg=function(a){xg();if(a=a||null){var b=m.Fg(),c=!0;b&&b.getVideoData&&(c=b.getVideoData(),c=c.video_id!=a.args.video_id||c.list!=a.args.list);c?(Hg="",m.tg("player-api",a)):b.playVideo();a=m.Nd(a);a.loaded=!0}Eg();m.l("ytplayer.config",a,void 0)};
m.Fg=function(){var a=m.n("yt.player.getPlayerByElement");return a?a("player-api"):null};var Eg=function(){var a=m.G("player"),b=m.Fg();if(a&&b){var a=a&&m.C(a,"off-screen"),c=1==(b&&b.isReady()?b.getPlayerState():void 0),d="watch"==m.v("PAGE_NAME");c&&!d&&(Gg("PP playing off watch (paused)"),b.pauseVideo());a&&d?Gg("PP off-screen on watch"):a||d||Gg("PP !off-screen off watch")}};
var Gg=function(a){var b=m.v("PAGE_NAME");b&&(b=[b,Hg,m.n("_spf_state.nav-counter")],a+="("+b.join(",")+")",m.l("yt.www.persistentplayer.issue",a,void 0),m.eb(Error(a),"WARNING"))};var Ig=function(){m.Sc("ol");Jg("init");var a=m.v("PAGE_NAME");a&&Jg("init-"+a);jd()};var Jg=function(a){m.kd()?Kg.push(m.md(m.r(m.ob,a),0)):m.A(a)};var Lg=function(){m.pd(Kg);Kg.length=0;var a=m.v("PAGE_NAME");a&&m.ob("dispose-"+a);m.ob("dispose")};var Mg=function(){Ig()};
var Ng=function(){m.v("TIMING_REPORT_ON_UNLOAD")&&id(!0);m.v("EXP_DEFER_CSI_PING")&&fd("u");Lg()};var Og=function(a,b,c,d,e){for(var f=window.document.getElementsByTagName("script"),h=!1,k=0,p=f.length;k<p;k++)if(0<f[k].src.indexOf("/debug-")){h=!0;break}h&&(e||(e=Error(),e.message=a,e.fileName=b,e.lineNumber=c,(0,window.isNaN)(d)||(e.columnNumber=d)),m.eb(e))};
var Pg=function(){Qg=1;Rg=0;m.v("TIMING_REPORT_ON_UNLOAD")&&id(!0);m.v("EXP_DEFER_CSI_PING")&&fd("n");cd(void 0);dd();m.v("CSI_TRACK_ON_BEGIN")&&Vc("nb");Uc("mark_navigation_requested");Sg(Tg);m.ob("navigate")};var Ug=function(a){a=a.detail.part||a.detail.partial;m.Sc("nc"+Rg);++Rg;var b=1==Qg;Qg=2;b?(Sg(Vg),Wg()):Sg(Xg);(a=a.data&&a.data.swfcfg)&&Yg(a)};var Zg=function(){};var $g=function(a){a=a.detail.response;var b=1==Qg;Qg=3;b&&(Sg(ah),Wg());(a=a.data&&a.data.swfcfg)&&Yg(a)};
var bh=function(a){m.Sc("nd");a=a.detail.response;m.ch=a.cacheKey;a=a.timing;var b=window._spf_state,b=b&&b["nav-counter"]||0;Wc(void 0).yt_nav=b;Vc("ne",a.responseStart);b=Math.max(0,a.responseStart-a.navigationStart);Wc(void 0).srt=b;b=a.spfCached?"hot":"warm";Wc(void 0).yt_lt=b;b=+!!a.spfPrefetched;Wc(void 0).yt_pft=b;a=a.responseStart-a.fetchStart;ad(void 0).span.req=a;Sg(dh);window.document.getElementById("content").style.height="";Ig();Qg=0};
var eh=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),m.eb(a)};var fh=function(a){a=m.Mc({spfreload:"1",url:a.detail.url,reason:a.detail.reason});m.Id(a)};var gh=function(){hh()};var ih=function(){};
var Wg=function(){window.scroll(0,0);var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");Lg();for(var b in m.$a)delete m.$a[b];m.l("ytplayer.config",null,void 0);if((a=m.Fg())&&a.stopVideo){if(a.stopVideo(),a=a.getLastError())Hg=a,(a=m.G("movie_player"))&&a.stopVideo?(a.stopVideo(),Hg="recovered"):Hg="missing2"}else Hg="missing";Eg()};var Yg=function(a){"cfg"in Tc(void 0)||m.Sc("cfg");Cg(a)};
var Sg=function(a){function b(){var b=a[0],e=a[1],f=a[2];c.className="";var h=c.style;h.transitionDuration=h.webkitTransitionDuration=b+"ms";h.width=e+"%";m.cb(jh);jh=m.x(function(){c.className=f},b)}var c=window.document.getElementById("progress");c||(c=window.document.createElement("div"),c.id="progress",c.innerHTML="<dt><dd>",window.document.body.appendChild(c));m.ld()?(m.od(kh),kh=m.md(b,0)):(m.cb(jh),jh=m.x(b,0))};
var hh=function(){var a=dh[0]+50;m.cb(jh);jh=m.x(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};var lh=function(){var a=!1;640>(window.innerWidth||window.document.documentElement.clientWidth)&&(a=!0);m.rb(m.G("player"),"watch-tiny",a);m.rb(window.document.body,"watch-while-skinny",a)};var mh=function(){m.qd.call(this,"www/base");this.g=0};var nh=function(a){(a=a.detail.name)&&ud(a)};m.ba=[];m.oh=m.oh||{};m.da=this;
pa="closure_uid_"+(1E9*Math.random()>>>0);qa=0;m.I=Date.now||function(){return+new Date};Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return m.q.apply(null,c)}return(0,m.q)(this,a)};m.ta[" "]=m.ea;m.t(m.ua,Error);m.ua.prototype.name="CustomError";var ya,za,Aa,Ba,Ca,Da,xa;m.Ha=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};ya=/&/g;za=/</g;Aa=/>/g;Ba=/"/g;Ca=/'/g;Da=/\x00/g;xa=/[\x00&<>"']/;m.ph=2147483648*Math.random()|0;m.Sa=Array.prototype;m.Pa=m.Sa.indexOf?function(a,b,c){return m.Sa.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(m.ja(a))return m.ja(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
m.qh=m.Sa.lastIndexOf?function(a,b,c){return m.Sa.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(m.ja(a))return m.ja(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};m.z=m.Sa.forEach?function(a,b,c){m.Sa.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.ja(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
m.qb=m.Sa.filter?function(a,b,c){return m.Sa.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=m.ja(a)?a.split(""):a,k=0;k<d;k++)if(k in h){var p=h[k];b.call(c,p,k,a)&&(e[f++]=p)}return e};m.rh=m.Sa.map?function(a,b,c){return m.Sa.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=m.ja(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};
m.sh=m.Sa.reduce?function(a,b,c,d){d&&(b=(0,m.q)(b,d));return m.Sa.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,m.z)(a,function(c,h){e=b.call(d,e,c,h,a)});return e};m.th=m.Sa.some?function(a,b,c){return m.Sa.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.ja(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};
m.uh=m.Sa.every?function(a,b,c){return m.Sa.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.ja(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};m.u.prototype.kb=!1;m.u.prototype.fa=function(){return this.kb};m.u.prototype.dispose=function(){this.kb||(this.kb=!0,this.M())};m.u.prototype.M=function(){if(this.va)for(;this.va.length;)this.va.shift()()};m.t(m.Xa,m.u);m.g=m.Xa.prototype;m.g.Uo=1;m.g.Ph=0;m.g.subscribe=function(a,b,c){var d=this.Nb[a];d||(d=this.Nb[a]=[]);var e=this.Uo;this.wa[e]=a;this.wa[e+1]=b;this.wa[e+2]=c;this.Uo=e+3;d.push(e);return e};m.g.unsubscribe=function(a,b,c){if(a=this.Nb[a]){var d=this.wa;if(a=m.Ma(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.Ib(a)}return!1};
m.g.Ib=function(a){if(0!=this.Ph)return this.g||(this.g=[]),this.g.push(a),!1;var b=this.wa[a];if(b){var c=this.Nb[b];c&&m.Qa(c,a);delete this.wa[a];delete this.wa[a+1];delete this.wa[a+2]}return!!b};m.g.publish=function(a,b){var c=this.Nb[a];if(c){this.Ph++;for(var d=Array(arguments.length-1),e=1,f=arguments.length;e<f;e++)d[e-1]=arguments[e];e=0;for(f=c.length;e<f;e++){var h=c[e];this.wa[h+1].apply(this.wa[h+2],d)}this.Ph--;if(this.g&&0==this.Ph)for(;c=this.g.pop();)this.Ib(c);return 0!=e}return!1};
m.g.clear=function(a){if(a){var b=this.Nb[a];b&&((0,m.z)(b,this.Ib,this),delete this.Nb[a])}else this.wa.length=0,this.Nb={}};m.g.ta=m.aa(3);m.g.M=function(){m.Xa.K.M.call(this);delete this.wa;delete this.Nb;delete this.g};m.$a=window.yt&&window.yt.config_||{};m.l("yt.config_",m.$a,void 0);m.l("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);m.gb=window.yt&&window.yt.msgs_||{};m.l("yt.msgs_",m.gb,void 0);m.Re="Microsoft Internet Explorer"==window.navigator.appName;var vh=m.n("yt.pubsub.instance_")||new m.Xa;m.Xa.prototype.subscribe=m.Xa.prototype.subscribe;m.Xa.prototype.unsubscribeByKey=m.Xa.prototype.Ib;m.Xa.prototype.publish=m.Xa.prototype.publish;m.Xa.prototype.clear=m.Xa.prototype.clear;m.l("yt.pubsub.instance_",vh,void 0);var kb=m.n("yt.pubsub.subscribedKeys_")||{};m.l("yt.pubsub.subscribedKeys_",kb,void 0);var mb=m.n("yt.pubsub.topicToKeys_")||{};m.l("yt.pubsub.topicToKeys_",mb,void 0);var lb=m.n("yt.pubsub.isSynchronous_")||{};
m.l("yt.pubsub.isSynchronous_",lb,void 0);m.jb=m.n("yt.pubsub.skipSubId_")||null;m.l("yt.pubsub.skipSubId_",m.jb,void 0);var zb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");var Ub=m.Ab("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));m.wh=RegExp("^[^\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");m.xh=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");m.Bb.prototype.af=!0;m.Bb.prototype.$e=function(){return this.g};m.Bb.prototype.toString=function(){return"Const{"+this.g+"}"};var Cb={};Eb.prototype.af=!0;var Fb={};Eb.prototype.$e=function(){return this.g};var Sb=Gb(""),Rb=/^[-.%_!# a-zA-Z0-9]+$/;Hb.prototype.af=!0;Hb.prototype.$e=function(){return""};Hb.prototype.Dk=!0;Hb.prototype.ag=function(){return 1};var Ib={};Jb.prototype.af=!0;Jb.prototype.$e=function(){return""};Jb.prototype.Dk=!0;Jb.prototype.ag=function(){return 1};var Kb={};var Pb,Tb,Qb,Mb;Lb.prototype.Dk=!0;Lb.prototype.ag=function(){return this.j};Lb.prototype.af=!0;Lb.prototype.$e=function(){return this.g};Pb=/^[a-zA-Z0-9-]+$/;Tb=m.Ab("action","cite","data","formaction","href","manifest","poster","src");Qb=m.Ab("embed","iframe","link","script","style","template");Mb={};m.yh=Xb("",0);t:{var zh=m.da.navigator;if(zh){var Ah=zh.userAgent;if(Ah){m.$b=Ah;break t}}m.$b=""};var Ch,dc,cc,Hh;m.$e=Zb("Opera")||Zb("OPR");m.F=Zb("Trident")||Zb("MSIE");m.Ze=Zb("Gecko")&&!m.Ea(m.$b.toLowerCase(),"webkit")&&!(Zb("Trident")||Zb("MSIE"));m.Ye=m.Ea(m.$b.toLowerCase(),"webkit");m.Ye&&Zb("Mobile");m.We=Zb("Macintosh");m.Ve=Zb("Windows");m.Bh=Zb("Linux")||Zb("CrOS");Ch=m.da.navigator||null;m.Dh=!!Ch&&m.Ea(Ch.appVersion||"","X11");m.Eh=Zb("Android");m.Fh=Zb("iPhone")&&!Zb("iPod")&&!Zb("iPad");m.Gh=Zb("iPad");
dc=function(){var a="",b;if(m.$e&&m.da.opera)return a=m.da.opera.version,m.la(a)?a():a;m.Ze?b=/rv\:([^\);]+)(\)|;)/:m.F?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:m.Ye&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(m.$b))?a[1]:"");return m.F&&(b=ac(),b>(0,window.parseFloat)(a))?String(b):a}();cc={};Hh=m.da.document;m.fc=Hh&&m.F?ac()||("CSS1Compat"==Hh.compatMode?(0,window.parseInt)(dc,10):5):void 0;var nc;nc=!m.F||m.ec(9);m.Ih=!m.Ze&&!m.F||m.F&&m.ec(9)||m.Ze&&m.bc("1.9.1");m.Jh=m.F&&!m.bc("9");m.Kh=m.F||m.$e||m.Ye;m.Lh=m.F&&!m.ec(9);var kc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};m.Mh=m.vc(!1);m.Nh=m.vc(!0);m.zc="StopIteration"in m.da?m.da.StopIteration:Error("StopIteration");m.xc.prototype.next=function(){throw m.zc;};m.xc.prototype.fb=function(){return this};var Gc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,Ec=m.Ye;var hg=/^https?:\/\/([A-Za-z0-9-]{1,63}\.)*(corp\.google\.com|borg\.google\.com|prod\.google\.com|video\.google\.com|youtube\.com|youtube\.googleapis\.com|youtube-nocookie\.com|youtubeeducation\.com)(:[0-9]+)?\/+embed\/+/;var Rc={},Qc=0,Oh=m.n("yt.net.ping.workerUrl_")||null;m.l("yt.net.ping.workerUrl_",Oh,void 0);var ed,gd,hd;var Yc=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{},dd=(0,m.q)(Yc.clearResourceTimings||Yc.webkitClearResourceTimings||Yc.mozClearResourceTimings||Yc.msClearResourceTimings||Yc.oClearResourceTimings||m.ea,Yc),Uc=Yc.mark?function(a){Yc.mark(a)}:m.ea;m.g=m.qd.prototype;m.g.hx=function(){2==this.j||this.init()};m.g.enable=function(){this.j=1;(0,m.z)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.hx,this),this.subscribe("dispose-"+a,this.dispose,this),m.v("PAGE_NAME")==a&&m.rd(this))},this)};m.g.init=function(){m.ld()&&m.od(this.k);this.j=2;this.B&&this.B()};m.g.dispose=function(){this.j=3;m.od(this.k);this.A&&this.A()};m.g.disable=function(){this.j=4;this.clear();this.dispose()};
m.g.subscribe=function(a,b,c){a=m.y(a,b,c);this.wa.push(a);return a};m.g.clear=function(){m.nb(this.wa);this.wa=[]};var td=m.n("yt.modules.registry_")||{};m.l("yt.modules.registry_",td,void 0);var xd={};var Cd=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,Dd=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;m.Hd=m.Fc;var Kd={enablejsapi:1},Ld={},Md={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};Jd.prototype.clone=function(){var a=new Jd,b;for(b in this){var c=this[b];"object"==m.ga(c)?a[b]=m.xb(c):a[b]=c}return a};m.Pd=null;m.Ph=m.Ye?"webkit":m.Ze?"moz":m.F?"ms":m.$e?"o":"";m.Qh=m.n("yt.dom.getNextId_");if(!m.Qh){m.Qh=function(){return++Rh};m.l("yt.dom.getNextId_",m.Qh,void 0);var Rh=0};m.g=m.Sd.prototype;m.g.ua=null;m.g.type="";m.g.target=null;m.g.relatedTarget=null;m.g.currentTarget=null;m.g.data=null;m.g.source=null;m.g.state=null;m.g.keyCode=0;m.g.charCode=0;m.g.altKey=!1;m.g.ctrlKey=!1;m.g.shiftKey=!1;m.g.clientX=0;m.g.clientY=0;m.g.wheelDeltaX=0;m.g.wheelDeltaY=0;m.g.rotation=0;m.g.scale=1;m.g.changedTouches=null;m.g.preventDefault=m.aa(4);m.g.stopPropagation=m.aa(5);m.g.stopImmediatePropagation=m.aa(6);
var Td={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1};m.Vd=m.n("yt.events.listeners_")||{};m.l("yt.events.listeners_",m.Vd,void 0);var Wd=m.n("yt.events.counter_")||{count:0};m.l("yt.events.counter_",Wd,void 0);m.Zd=/\s*;\s*/;m.g=m.Xd.prototype;m.g.isEnabled=m.aa(7);m.g.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');m.ca(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,m.I)()+1E3*c)).toUTCString();this.g.cookie=a+"="+b+e+d+c+f};
m.g.get=function(a,b){for(var c=a+"=",d=(this.g.cookie||"").split(m.Zd),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};m.g.remove=function(a,b,c){var d=m.ca(this.get(a));this.set(a,"",0,b,c);return d};m.g.Sa=m.aa(8);m.g.xa=m.aa(9);m.g.isEmpty=m.aa(10);m.g.ta=m.aa(2);m.g.uf=m.aa(11);m.g.clear=function(){for(var a=m.Yd(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};m.ae=new m.Xd(window.document);m.ae.j=3950;var te;var ne,pe=!1,qe=[];m.we.prototype.then=function(a,b,c){return m.De(this,m.la(a)?a:null,m.la(b)?b:null,c)};m.ue(m.we);m.we.prototype.cancel=function(a){0==this.j&&me(function(){var b=new Ee(a);ze(this,b)},this)};m.we.prototype.G=function(a){this.j=0;xe(this,2,a)};m.we.prototype.J=function(a){this.j=0;xe(this,3,a)};m.we.prototype.H=function(){for(;this.g&&this.g.length;){var a=this.g;this.g=[];for(var b=0;b<a.length;b++)Ae(this,a[b],this.j,this.C)}this.B=!1};var He=ke;m.t(Ee,m.ua);Ee.prototype.name="cancel";var Le=null;Ie.prototype.A=function(a){Me(this,"startFeedback",arguments)};Ie.prototype.B=function(a){Me(this,"startHelp",arguments)};Ie.prototype.g=function(a){Me(this,"loadChatSupport",arguments)};var Sh=!1,Th="";
if(window.navigator.plugins&&window.navigator.plugins.length){var Uh=window.navigator.plugins["Shockwave Flash"];Uh&&(Sh=!0,Uh.description&&(Th=Oe(Uh.description)));window.navigator.plugins["Shockwave Flash 2.0"]&&(Sh=!0,Th="2.0.0.11")}else if(window.navigator.mimeTypes&&window.navigator.mimeTypes.length){var Vh=window.navigator.mimeTypes["application/x-shockwave-flash"];(Sh=Vh&&Vh.enabledPlugin)&&(Th=Oe(Vh.enabledPlugin.description))}else try{var Wh=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),Sh=
!0,Th=Oe(Wh.GetVariable("$version"))}catch(aaa){try{Wh=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),Sh=!0,Th="6.0.21"}catch(baa){try{Wh=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash"),Sh=!0,Th=Oe(Wh.GetVariable("$version"))}catch(caa){}}}m.Xh=Sh;m.Yh=Th;var Zh,$h,ai,bi,ci,di,ei,hi,ki;ei=di=ci=bi=ai=$h=Zh=!1;var fi=m.$b;fi&&(-1!=fi.indexOf("Firefox")?Zh=!0:-1!=fi.indexOf("Camino")?$h=!0:-1!=fi.indexOf("iPad")?bi=!0:-1!=fi.indexOf("iPhone")||-1!=fi.indexOf("iPod")?ai=!0:-1!=fi.indexOf("Chrome")?di=!0:-1!=fi.indexOf("Android")?ci=!0:-1!=fi.indexOf("Safari")&&(ei=!0));m.gi=Zh;hi=$h;m.ii=ai;m.ji=bi;ki=ci;m.li=di;m.mi=ei;m.ni=function(){if(m.gi)return Pe(/Firefox\/([0-9.]+)/);if(m.F||m.$e)return dc;if(m.li)return Pe(/Chrome\/([0-9.]+)/);if(m.mi)return Pe(/Version\/([0-9.]+)/);if(m.ii||m.ji){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(m.$b))return a[1]+"."+a[2]}else{if(ki)return(a=Pe(/Android\s+([0-9.]+)/))?a:Pe(/Version\/([0-9.]+)/);if(hi)return Pe(/Camino\/([0-9.]+)/)}return""}();m.fa(Qe);Qe.prototype.getVersion=function(){return[this.g,this.j,this.k]};m.g=m.bf.prototype;m.g.clone=function(){return new m.bf(this.top,this.right,this.bottom,this.left)};m.g.contains=function(a){return m.cf(this,a)};m.g.ceil=m.aa(12);m.g.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};m.g.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
m.g.scale=function(a,b){var c=m.ka(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};m.oi=m.wc(function(){if(m.F)return m.bc("10.0");var a=window.document.createElement("div"),b=m.af(),c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");b=m.Ob("div",{style:c});a.innerHTML=m.Nb(b);a=a.firstChild;b=a.style[m.Ja("transition")];return""!=("undefined"!==typeof b?b:a.style[m.df(a,"transition")]||"")});var nf;m.jf={};nf=!1;m.fa(m.pf);m.qf=m.n("yt.prefs.UserPrefs.prefs_")||{};m.l("yt.prefs.UserPrefs.prefs_",m.qf,void 0);m.g=m.pf.prototype;m.g.get=function(a,b){sf(a);rf(a);var c=void 0!==m.qf[a]?m.qf[a].toString():null;return null!=c?c:b?b:""};m.g.set=function(a,b){sf(a);rf(a);if(null==b)throw"ExpectedNotNull";m.qf[a]=b.toString()};m.g.remove=function(a){sf(a);rf(a);delete m.qf[a]};m.g.save=function(){var a;a=[];for(var b in m.qf)a.push(b+"="+(0,window.escape)(m.qf[b]));a=a.join("&");m.$d("PREF",a,63072E3)};
m.g.clear=function(){m.qf={}};var Df=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var Ff;var pi=m.$b,pi=pi.toLowerCase();if(m.Ea(pi,"android")){var qi=pi.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(qi)Ff=Number(qi[1]);else{var ri={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},si=pi.match("("+m.tb(ri).join("|")+")");Ff=si?ri[si[0]]:0}}else Ff=void 0;m.t(m.Hf,Gf);m.Hf.prototype.ta=m.aa(1);m.Hf.prototype.clear=function(){var a=m.Bc(this.fb(!0)),b=this;(0,m.z)(a,function(a){b.remove(a)})};m.t(m.If,m.Hf);m.g=m.If.prototype;m.g.isAvailable=function(){if(!this.g)return!1;try{return this.g.setItem("__sak","1"),this.g.removeItem("__sak"),!0}catch(a){return!1}};m.g.set=function(a,b){try{this.g.setItem(a,b)}catch(c){if(0==this.g.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};m.g.get=function(a){a=this.g.getItem(a);if(!m.ja(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};m.g.remove=function(a){this.g.removeItem(a)};
m.g.ta=m.aa(0);m.g.fb=function(a){var b=0,c=this.g,d=new m.xc;d.next=function(){if(b>=c.length)throw m.zc;var d;d=c.key(b++);if(a)return d;d=c.getItem(d);if(!m.ja(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};m.g.clear=function(){this.g.clear()};m.g.key=function(a){return this.g.key(a)};m.t(m.Jf,m.If);m.t(Kf,m.If);var Sf={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Rf=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;m.Tf.prototype.set=function(a,b){m.ca(b)?this.g.set(a,m.Mf(b)):this.g.remove(a)};m.Tf.prototype.get=function(a){var b;try{b=this.g.get(a)}catch(c){return}if(null!==b)try{return m.Lf(b)}catch(d){throw"Storage: Invalid value was encountered";}};m.Tf.prototype.remove=function(a){this.g.remove(a)};m.t(Uf,m.Tf);Uf.prototype.set=function(a,b){Uf.K.set.call(this,a,Wf(b))};Uf.prototype.j=function(a){a=Uf.K.get.call(this,a);if(!m.ca(a)||a instanceof Object)return a;throw"Storage: Invalid value was encountered";};Uf.prototype.get=function(a){if(a=this.j(a)){if(a=a.data,!m.ca(a))throw"Storage: Invalid value was encountered";}else a=void 0;return a};m.t(Xf,Uf);Xf.prototype.set=function(a,b,c){if(b=Wf(b)){if(c){if(c<(0,m.I)()){Xf.prototype.remove.call(this,a);return}b.expiration=c}b.creation=(0,m.I)()}Xf.K.set.call(this,a,b)};Xf.prototype.j=function(a,b){var c=Xf.K.j.call(this,a);if(c)if(!b&&m.Yf(c))Xf.prototype.remove.call(this,a);else return c};m.t(m.Zf,Xf);var ti,ui;ti=new m.Jf;m.ag=ti.isAvailable()?new m.Zf(ti):null;ui=new Kf;m.bg=ui.isAvailable()?new m.Zf(ui):null;m.t(eg,m.u);m.g=eg.prototype;m.g.getId=function(){return this.H};m.g.lj=function(a,b){this.fa()||(gg(this,a),ng(this,b),this.C&&jg(this))};m.g.vt=function(){return this.Aa};
m.g.Fy=function(){if(!this.N){var a=og(this);a&&"html5"==rg(this)?(this.B="html5",this.C||this.Ke()):(sg(this),this.B="html5",a&&this.ga?(this.vf.appendChild(this.ga),this.Ke()):(this.da.loaded=!0,this.G=(0,m.q)(function(){var a=this.vf,c=this.da.clone();m.n("yt.player.Application.create")(a,c);this.Ke()},this),this.N=!0,a?this.G():(m.yd(this.da.assets.js,this.G),m.Cf(this.da.assets.css))))}};
m.g.Ey=function(){var a=this.da.clone();a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==rg(this)?(this.B="flash",this.C||Af(a,!1,(0,m.q)(this.Ke,this))):(sg(this),this.B="flash",this.da.loaded=!0,m.wf(this.vf,a),this.Ke())};
m.g.Ke=function(){var a=mg(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(c){}if(b)if(this.N=!1,a.isNotServable&&a.isNotServable())lg(this);else{fg(this);this.C=!0;a=mg(this);a.addEventListener&&(this.J=pg(this,a,"addEventListener"));a.removeEventListener&&(this.U=pg(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),d=0;d<b.length;d++){var e=b[d];this.g[e]||(this.g[e]=pg(this,a,e))}for(var f in this.A)this.J(f,this.A[f]);jg(this);
this.X&&this.X(this.g);this.O.publish("onReady",this.g)}else this.za=m.x((0,m.q)(this.Ke,this),50)};m.g.At=function(){return this.C};m.g.ue=function(a,b){if(!this.fa()){var c=ig(this,b);if(c){if(!m.Oa(this.Fa,a)&&!this.A[a]){var d=qg(this,a);this.J&&this.J(a,d)}this.O.subscribe(a,c);"onReady"==a&&this.C&&m.x(m.r(c,this.g),0)}}};m.g.zt=function(a,b){if(!this.fa()){var c=ig(this,b);c&&this.O.unsubscribe(a,c)}};
m.g.Pp=function(a){a=a?sc:rc;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||(b.focus(),b!=window.document.activeElement));)b=a(b)};m.g.Rp=function(a){var b={};b.volume=(0,window.isNaN)(a.volume)?dg().volume:m.Yb(a.volume,0,100);b.muted=void 0==a.muted?dg().muted:a.muted;m.$f("yt-player-volume",b,2592E3)};m.g.Qp=function(a){5==a&&lg(this)};m.g.Sp=function(a){m.A("WATCH_LATER_VIDEO_ADDED",a)};m.g.Tp=function(a){m.A("WATCH_LATER_VIDEO_REMOVED",a)};
m.g.Gy=function(){sg(this);this.B="unsupported";var a='Adobe Flash Player or an HTML5 supported browser is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="/html5">Learn more about upgrading to an HTML5 browser</a>',b=window.navigator.userAgent.match(/Version\/(\d).*Safari/);b&&5<=(0,window.parseInt)(b[1],10)&&(a='Adobe Flash Player or QuickTime is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/"> Get the latest Flash Player</a> <br> <a href="http://www.apple.com/quicktime/download/">Get the latest version of QuickTime</a>');
b=this.da.messages.player_fallback||a;a=m.G("player-unavailable");m.G("unavailable-submessage")&&a&&(m.G("unavailable-submessage").innerHTML=b,(b=m.H("icon",a))&&m.wd(b,"icon")&&(b.src=m.J(b,"icon")),m.E(a,"hid"),m.D(m.G("player"),"off-screen-trigger"))};m.g.xt=function(){return this.B||rg(this)};m.g.wt=function(){return this.oa};m.g.cancel=function(){this.G&&m.Ad(this.da.assets.js,this.G);m.cb(this.za);this.N=!1};
m.g.M=function(){sg(this);this.$=null;for(var a in this.A)m.da[this.A[a]]=null;this.g=null;delete this.vf;delete this.k;this.da&&(this.Aa=this.da=this.da.fallback=null);eg.K.M.call(this)};var vg={},ug="player_uid_"+(1E9*Math.random()>>>0);var vi=m.n("yt.abuse.botguardInitialized")||Od;m.l("yt.abuse.botguardInitialized",vi,void 0);var wi=m.n("yt.abuse.invokeBotguard")||m.Qd;m.l("yt.abuse.invokeBotguard",wi,void 0);var xi=m.n("yt.player.exports.navigate")||m.je;m.l("yt.player.exports.navigate",xi,void 0);var yi=m.n("yt.player.embed")||m.tg;m.l("yt.player.embed",yi,void 0);var zi=m.n("yt.player.destroy")||m.yg;m.l("yt.player.destroy",zi,void 0);var Ai=m.n("yt.player.cancelAll")||xg;m.l("yt.player.cancelAll",Ai,void 0);
var Bi=m.n("yt.player.getPlayerByElement")||m.Ag;m.l("yt.player.getPlayerByElement",Bi,void 0);var Ci=m.n("yt.player.exports.feedbackStart")||m.lf;m.l("yt.player.exports.feedbackStart",Ci,void 0);var Di=m.n("yt.player.exports.feedbackShowArticle")||m.of;m.l("yt.player.exports.feedbackShowArticle",Di,void 0);var Ei=m.n("yt.util.activity.init")||m.ce;m.l("yt.util.activity.init",Ei,void 0);var Fi=m.n("yt.util.activity.getTimeSinceActive")||m.ee;m.l("yt.util.activity.getTimeSinceActive",Fi,void 0);
var Gi=m.n("yt.util.activity.setTimestamp")||de;m.l("yt.util.activity.setTimestamp",Gi,void 0);var Dg,Hg="";var Kg=[];var Qg,jh,kh,Rg,Tg,ah,Vg,Xg,dh;Rg=0;Tg=[900,60,"waiting"];ah=[500,99,"waiting"];Vg=[300,60,"waiting"];Xg=[400,99,"waiting"];dh=[300,101,"done"];var Hi=[];window.yt=window.yt||{};m.l("yt.setConfig",m.Ya,void 0);m.l("yt.getConfig",m.v,void 0);m.l("yt.hasMsg",m.fb,void 0);m.l("yt.pubsub.publish",m.A,void 0);m.l("yt.pubsub.subscribe",m.y,void 0);m.l("yt.setMsg",function(a){Za(m.gb,arguments)},void 0);m.l("yt.setGoogMsg",function(a){Za(m.gb,arguments)},void 0);m.l("yt.setAjaxToken",function(){},void 0);
m.l("reportTimingMaps",function(a,b,c,d){if(a)for(var e in a)m.Sc(e,a[e],d);if(c)for(var f in c)if("number"==typeof c[f])a=f,e=c[f],ad(d).span[a]=e;else{a=f;e=c[f];var h=d,k=ad(h).span,h=Tc(h);e in h&&(k[a]=(0,m.I)()-h[e])}if(b)for(var p in b)c=p,f=b[p],Wc(d)[c]=f;return jd(d)},void 0);
m.l("yt.timing.reportAdToVideo",function(a,b,c){c={v:2,s:"youtube",action:c?"watch,ad2video_html5":"watch,ad2video"};a.aft=a.pbs=a.astv||a.actv;var d=[],e;for(e in a)"_"!=e.charAt(0)&&d.push(e+"."+a[e]);c.rt=d.join(",");for(var f in b)"_"!=f.charAt(0)&&(c[f]=b[f]);a=m.v("TIMING_INFO")||{};"e"in a&&(c.e=a.e);"ei"in a&&(c.ei=a.ei);bd(c)},void 0);m.t(mh,m.qd);
mh.prototype.enable=function(){window.onload=Mg;window.onunload=Ng;window.onerror=Og;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfrequest",Pg),window.addEventListener("spfpartprocess",Ug),window.addEventListener("spfpartdone",Zg),window.addEventListener("spfprocess",$g),window.addEventListener("spfdone",bh),window.addEventListener("spferror",eh),window.addEventListener("spfreload",fh),window.addEventListener("spfjsbeforeunload",nh)),a.config=a.config||{},
window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",gh),this.subscribe("dispose",ih)):window.spf.dispose();this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
mh.prototype.init=function(){mh.K.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();var a=window.ytPageFrameLoaded||!1,b,c;!a&&m.v("PAGEFRAME_JS")?(b=m.v("PAGEFRAME_JS"),c=function(){m.n("ytbin.www.pageframe.setup")();window.ytPageFrameLoaded=!0}):a&&(a=m.n("yt.www.masthead.loadSearchbox"))&&a();var a=m.v("JS_COMMON_MODULE"),d=m.v("JS_PAGE_MODULES");if(window.ytdepmap)d||(d=[a]),a=m.v("JS_DELAY_LOAD",void 0),0<a?(m.cb(this.g),this.g=m.x(function(){b&&m.yd(b,c);window.spf.script.require(d)},
a)):(b&&m.yd(b,c),window.spf.script.require(d));else{var e={};e[a]=d;a=m.v("JS_DELAY_LOAD",void 0);0<a?(m.cb(this.g),this.g=m.x(function(){b&&m.yd(b,c);m.Bd(e)},a)):(b&&m.yd(b,c),m.Bd(e))}m.v("SKYWATCH_ENABLED")&&(Hi.push(m.y("page-resize",lh)),lh());Bg();var a=!!m.n("yt.reactLoaded"),f=m.v("REACT_JS");!a&&f&&m.yd(f,function(){m.l("yt.reactLoaded",!0,void 0)})};
mh.prototype.dispose=function(){m.cb(this.g);var a=m.n("ytbin.www.pageframe.cancelSetup");a&&a();m.nb(Hi);Hi.length=0;m.db(Dg);if(a=m.Fg())a.removeEventListener("onReady",Eg),a.removeEventListener("onStateChange",Eg);mh.K.dispose.call(this)};
mh.prototype.disable=function(){mh.K.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfrequest",Pg),window.removeEventListener("spfpartprocess",Ug),window.removeEventListener("spfpartdone",Zg),window.removeEventListener("spfprocess",$g),window.removeEventListener("spfdone",bh),window.removeEventListener("spferror",eh),window.removeEventListener("spfreload",fh),window.removeEventListener("spfjsbeforeunload",nh));window.onload=null;window.onunload=null;window.onerror=null};
m.sd(new mh);})(_yt_www);
